apiVersion: v1
kind: Service
metadata:
  labels:
    app: block-buster
  name: block-buster-service--7-7-0
  namespace: 7-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: block-buster
    version: 7.7.0
    env: dev
  type: NodePort