apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgCvJqVM4BAxFFahUqUvUo8w+QsGeLgACEZJz8Sw4MIO8LoU8olD0xqAihJphU/3PfsKwG2CufzHfoPcX/alYuJTrmScuWzN18xAWAbtAJgVOB5i1auyZcNGs0T0mlGYtESiTwTgKomo8n4cDK/QmB01fd1roGCZwrOvLCiJfsg6i6sxLH7iW3ffzTMAmlzQkBbS1NFrvgWphbE60Ev3+iiUqd026K0ccY5uooVMEcs/OfATp32W5ZWFkzNsEtccFAoUy9Sz1RVOpr/6oKoxvJaLRz9vSea4QOP0jmoINsrDXsMI4E8oVMd34fKelSD3Z3OHZseYKXNUYk7RVsTox7pSeJueIvv1M01+CcowqpOKnsKb/GB0Y4x1CPjUl96hHMrY9HYYmQKOQ5FDPRXY9TjPpzJ9xGiVaMSfzX5fk87H4ePUovQQPU1wRRoW0+qeMeoxWsraf52xYD06AhGQLVOq0yUOb+2vG7LxAG/u6PZ8aZ7JnICnRmv5djUgn2p/VAcuk4KBN6SF1/q0T6+mSZIV0VvM3UEVMM6LTkVSk6K2Jx4ZzywjeHVH6ACXkwm/KhifBe34WquLetq5An2S7pb8aBAef9ulWA+LH6vcV5DiMGq1oOOoNWCHA/fbPJWK2XlkNHWyfJP3A02pWfTeZ+yTQKjEuI4F2+3H+OwRvB+zLzjaPpvnn/kvze7dPYKGAHLvlLbHw9NONlxSLAzItmyqBRQ8ADHlWKV8
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

