apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "block-buster-helm-app.fullname" . }}
  labels:
    app: {{ .Values.labels.app.name }}
    version: {{ .Values.labels.app.version }}
    env: {{ .Values.labels.app.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.labels.app.name }}
        version: {{ .Values.labels.app.version }}
        env: {{ .Values.labels.app.env }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP